<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Buscar livros</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container-fluid">
      <div class="navbar-brand mb-0 d-flex justify-content-center align-items-center" >
          <a href="home.html"
            ><img
              src="../../public/Books_imgs/even_little_book.png"
              class="img-fluid"
              alt="little_book"
          /></a>
          <strong><h2 class="pt-1">BookSpace</h2></strong>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsite">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsite">
            <ul class="navbar-nav mr-auto">
               
                <li class="nav-item">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navdrop">
                            Menu
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="./livro_cadastro.html">Cadastrar</a>
                            <a class="dropdown-item" href="./dados_usuario.html">Minha conta</a>
                            <a class="dropdown-item" href="./busca_livros.html">Categorias</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
           
            <form class="form-inline">
                <input class="form-control ml-2 " type="search" placeholder="search...">
                <button class="btn btn-warning" type="subtmit">search</button>
                <a href="login.html" class="btn btn-primary ml-3" id="login">login</a>
            </form>
        </div>
    </div>
  </nav>
    <div class="container-fluid">
          <div class="container" id="categories_content">
            <div class="row mt-4">
              <div class="col-md-3">
                <div class="card border-light card_filter">
                  <div class="card-header"><strong>Filtro</strong></div>
                  <div class="card-body">
                    <p class="card-text"><a href="#">Romance</a></p>
                    <p class="card-text"><a href="#">ação</a></p>
                    <p class="card-text"><a href="#">infanto-juvenil</a></p>
                    <p class="card-text"><a href="#">estrangeiro</a></p>
                    <p class="card-text"><a href="#">Biografias</a></p>
                    <p class="card-text"><a href="#">mangás/gibis</a></p>
                    <p class="card-text"><a href="#">terror/suspense</a></p>
                    <p class="card-text"><a href="#">auto ajuda</a></p>
                    <p class="card-text"><a href="#">religioso</a></p>
                    <p class="card-text"><a href="#">infantis</a></p>
                    <p class="card-text"><a href="#">acadêmicos</a></p>
                    <p class="card-text"><a href="#">fantasia</a></p>
                  </div>
                </div>
              </div>
              <div class="col-md-9" id="results_cards">
              <?php foreach($livros as $livro){?>
                <div class="card mb-4">
                  <div class="card-body d-flex ">
                    <div class="h-auto w-auto">
                      <img class="d-block w-50" src="../../public/Books_imgs/Diario_banana.jpg" >
                    </div>
                      <div class="book_information">
                        <div class="book_title mb-">
                          <h4 class="card-title"><?=$livro['Nome_Livro']?></h4>
                        </div>
                            <div class="price mb-">
                              <h5>R$ <?=$livro['Preço']?></h5>
                            </div>
                            <div class="location mb-">
                              <p> <?=$livro['Ano']?> </p>
                            </div>
                            <div class="visit_button">
                              <a href="#" class="btn btn-primary"> comprar</a>
                            </div>
                      </div>      
                  </div>
                </div>
                <?php } ?>
                <div class="card mb-4">
                  <div class="card-body d-flex ">
                    <div class="h-auto w-auto">
                      <img class="d-block w-50" src="../../public/Books_imgs/Diario_banana.jpg" >
                    </div>
                      <div class="book_information">
                        <div class="book_title mb-">
                          <h4 class="card-title">Exemplo</h4>
                        </div>
                            <div class="price mb-">
                              <h5>Exemplo</h5>
                            </div>
                            <div class="location mb-">
                              <p> Exemplo </p>
                            </div>
                            <div class="visit_button">
                              <a href="#" class="btn btn-primary"> comprar</a>
                            </div>
                      </div>      
                  </div>
                </div>            
               </div>
              </div>
              </div>    
             </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
