<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>my first test</title>
</head>
<body>
    <h1>Salvo</h1>
<p> Nome: <?= $livros['nome']  ?> </p>
<p> Ano: <?= $livros['ano']  ?> </p>
<p> Valor: <?= $livros['valor']  ?> </p>
<p> Idioma: <?= $livros['idioma']  ?> </p>
<p> Editora: <?= $livros['editora']  ?> </p>
<p> Edição: <?= $livros['edicao']  ?> </p>
<p> descrição: <?= $livros['descricao']  ?> </p>
<p> Quantidade de páginas: <?= $livros['quantidade_paginas']  ?> </p>
</body>
</html>